### ISSUE TITLE
Replace sharing info by our branding

### ISSUE THREAD

**Issue by jmastr** [planetmint/big-dipper-2.0-cosmos#6]
Currently, when someonse shares the link to our explorer https://explorer.rddl.io e.g. via Discord one sees the following preview:

![Screenshot from 2023-11-30 16-18-01](https://github.com/planetmint/big-dipper-2.0-cosmos/assets/11860038/0b19ffae-3fef-498a-ae46-c8cf057842ad)

This is the default picture and text from Big Dipper and should be changed to something Planetmint/RDDL related.

**Comment by GR3G0RYO** [comment]
Create ticket on Notion for Prod Dev team with github issue linked not zenhub.

**Comment by GR3G0RYO** [comment]
I will align with Gabriella and create the ticket for the Dev Team

**Comment by GR3G0RYO** [comment]
We just need a design here to have Julian place in the current images spot.

**Comment by GR3G0RYO** [comment]
examples RDDLx Big Dipper or Planetmintx Big Dipper

**Comment by eckelj** [comment]
in the repo:

https://github.com/planetmint/big-dipper-2.0-cosmos

create new image

https://github.com/planetmint/big-dipper-2.0-cosmos/blob/a1dee42a0167793d8f740aefbcea867f21019a87/apps/web-planetmint/src/chain.json#L8

and replace the link.
